" Enable filetype detection, plugin loading, and indent formatting.
filetype plugin indent on
" Enable syntax highlighting.
syntax on
" Specify system clipboard for copy+paste.
set clipboard=unnamed
" Set right-side boarder line.
set cc=80
" Enable backspace.
set backspace=indent,eol,start
" Show white spaces.
set list
" Set specific white space characters.
set listchars=trail:·,tab:>-
" Disable swap files.
set noswapfile
" Enable row and column display of cursor.
set ruler
" Set tab to four spaces.
set tabstop=4
" Indent corresponds to single tab.
set shiftwidth=4
" On pressing tab, insert spaces.
set expandtab

" Go syntax highlighting
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
