execute pathogen#infect()
filetype plugin indent on
syntax on
set shiftwidth=4
set tabstop=4
set expandtab
set backspace=indent,eol,start
set listchars=trail:·,tab:>-
set list
set ruler
set noswapfile
:set cc=80
au BufNewFile,BufRead *.md set filetype=markdown
set clipboard=unnamed

" Go syntax highlighting
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_bin_path = expand("~/bin")
